-- Tabela de Vendas & Trocas
CREATE TABLE public.marketplace_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    seller_name TEXT NOT NULL,
    seller_whatsapp TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    price NUMERIC,
    type TEXT DEFAULT 'Venda', -- 'Venda', 'Troca', 'Grátis'
    condition TEXT DEFAULT 'Usado', -- 'Novo', 'Usado'
    neighborhood TEXT NOT NULL,
    image TEXT,
    status TEXT DEFAULT 'Ativo' -- 'Ativo', 'Vendido'
);

ALTER TABLE public.marketplace_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo marketplace" ON public.marketplace_items FOR ALL USING (true);
