-- Execute este código no "SQL Editor" do seu painel do Supabase

-- Tabela de Usuários
CREATE TABLE public.profiles (
    id UUID DEFAULT auth.uid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    handle TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'Ativo',
    avatar TEXT,
    whatsapp TEXT,
    neighborhood TEXT,
    address TEXT,
    role TEXT DEFAULT 'user'
);

-- Tabela de Publicações (Posts)
CREATE TABLE public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    author_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    author_name TEXT NOT NULL,
    author_avatar TEXT,
    handle TEXT NOT NULL,
    category TEXT DEFAULT 'Geral',
    neighborhood TEXT NOT NULL,
    content TEXT,
    image TEXT,
    likes INTEGER DEFAULT 0,
    upvotes INTEGER DEFAULT 0,
    downvotes INTEGER DEFAULT 0,
    is_pending BOOLEAN DEFAULT true,
    is_approved BOOLEAN DEFAULT false
);

-- Tabela de Comentários
CREATE TABLE public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE,
    author_name TEXT NOT NULL,
    text TEXT NOT NULL
);

-- Tabela de Configurações Globais (Avisos e Limites)
CREATE TABLE public.settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value TEXT NOT NULL
);

-- Inserir as configurações padrão iniciais
INSERT INTO public.settings (key, value) VALUES 
('max_comments_per_post', '3'),
('global_announcement', '');

-- Habilitar RLS (Row Level Security) para proteção básica
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

-- Políticas de segurança: Permitir leitura e escrita para todos (Fase de Desenvolvimento)
-- ATENÇÃO: Num cenário real, alteraríamos para permitir apenas usuários autenticados
CREATE POLICY "Permitir tudo profiles" ON public.profiles FOR ALL USING (true);
CREATE POLICY "Permitir tudo posts" ON public.posts FOR ALL USING (true);
CREATE POLICY "Permitir tudo comments" ON public.comments FOR ALL USING (true);
CREATE POLICY "Permitir tudo settings" ON public.settings FOR ALL USING (true);
