-- Execute este código no "SQL Editor" do seu painel do Supabase para criar a tabela de solicitações de exclusão de conta

CREATE TABLE public.deletion_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_name TEXT NOT NULL,
    user_whatsapp TEXT NOT NULL,
    status TEXT DEFAULT 'Pendente' -- Pode ser 'Pendente' ou 'Excluída'
);

-- Habilitar RLS (Row Level Security)
ALTER TABLE public.deletion_requests ENABLE ROW LEVEL SECURITY;

-- Políticas de segurança: Permitir leitura e escrita para todos (ou ajustar conforme necessidade)
CREATE POLICY "Permitir tudo deletion_requests" ON public.deletion_requests FOR ALL USING (true);
