-- Execute este código no "SQL Editor" do seu painel do Supabase para criar a tabela de Pets Perdidos

CREATE TABLE public.lost_pets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    pet_name TEXT NOT NULL,
    species TEXT NOT NULL,
    description TEXT,
    last_seen_location TEXT NOT NULL,
    owner_whatsapp TEXT NOT NULL,
    image TEXT,
    status TEXT DEFAULT 'Perdido' -- Pode ser 'Perdido' ou 'Encontrado'
);

-- Habilitar RLS (Row Level Security)
ALTER TABLE public.lost_pets ENABLE ROW LEVEL SECURITY;

-- Políticas de segurança: Permitir leitura e escrita para todos
CREATE POLICY "Permitir tudo lost_pets" ON public.lost_pets FOR ALL USING (true);

-- Inserir um dado de exemplo
INSERT INTO public.lost_pets (pet_name, species, description, last_seen_location, owner_whatsapp, image, status)
VALUES 
('Bidu', 'Cachorro (Poodle)', 'Porte pequeno, branco, coleira azul. Muito dócil.', 'Praça da Matriz, Centro', '5511999999999', 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80', 'Perdido');
