-- Execute este código no "SQL Editor" do seu painel do Supabase para criar a tabela do Guia Comercial

CREATE TABLE public.commercial_guide (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    whatsapp TEXT NOT NULL,
    neighborhood TEXT DEFAULT 'Geral',
    rating NUMERIC DEFAULT 5.0,
    is_verified BOOLEAN DEFAULT true,
    image TEXT
);

-- Habilitar RLS (Row Level Security)
ALTER TABLE public.commercial_guide ENABLE ROW LEVEL SECURITY;

-- Políticas de segurança: Permitir leitura e escrita para todos (Fase de Desenvolvimento)
CREATE POLICY "Permitir tudo commercial_guide" ON public.commercial_guide FOR ALL USING (true);

-- Inserir alguns dados de exemplo (Seed) para você ver como fica na tela
INSERT INTO public.commercial_guide (name, category, description, whatsapp, neighborhood, rating, is_verified)
VALUES 
('João Eletricista', 'Serviços', 'Instalação, manutenção e reparos elétricos residenciais.', '5511999999999', 'Centro', 4.9, true),
('Pizzaria do Bairro', 'Alimentação', 'A melhor pizza da região, entrega grátis às terças!', '5511988888888', 'Jardim Primavera', 4.8, true),
('Maria Diarista', 'Limpeza', 'Limpeza pesada e organização de ambientes.', '5511977777777', 'Vila Nova', 5.0, true);
